Added Log collection post
project-flotta/flotta.github.io pull request #11
Opened 2022-04-11 09:21 UTC by eloycoto

Log collection post sharing how to enable logs on device level

Signed-off-by: Eloy Coto <eloy.coto@acalustra.com>

2022-04-11 14:35 UTC, jakub-dzon commented
@eloycoto GH shows no files in that commit/PR

2022-04-11 15:24 UTC, jakub-dzon requested changes
Good write-up and use case. 
I've got just a few comments.

2022-04-11 15:24 UTC, jakub-dzon commented on _posts/2022-04-10-using-log-collection.markdown
> +maybe differs from one site to another, as also the limit of data that can be
WDYT about "may differ"?

2022-04-11 15:24 UTC, jakub-dzon commented on _posts/2022-04-10-using-log-collection.markdown
> +maybe you don’t want that workload that manages any personal information sends
"maybe you don’t want workload that manages any personal information to send information outside the country"

2022-04-11 15:24 UTC, jakub-dzon commented on _posts/2022-04-10-using-log-collection.markdown
> +send the logs.
"to send the logs to."

2022-04-11 15:24 UTC, jakub-dzon commented on _posts/2022-04-10-using-log-collection.markdown
> +So the main use case is to be able to define servers in edge devices and be
"So the main use case is to be able to define servers in edge devices to be used by the workloads.". I didn't get what you had in mind in the other part of the sentence.

2022-04-11 15:24 UTC, jakub-dzon commented on _posts/2022-04-10-using-log-collection.markdown
> +big storing buffers. Meanwhile, there is a logGeneral, that it’s the server
Meanwhile ->  At the same time?
"that it’s the server" -> "that is the server that may lose logs on network downtime, or maybe using different transports"

2022-04-11 15:24 UTC, jakub-dzon commented on _posts/2022-04-10-using-log-collection.markdown
> +To collect logs, a subprocess reads the workloads stdout and pushed it to a
"and pushes"

2022-04-11 15:24 UTC, jakub-dzon commented on _posts/2022-04-10-using-log-collection.markdown
> +buffer, even if the device is network disconnected for a while, it’ll push the
"is disconnected from network"

2022-04-11 15:24 UTC, jakub-dzon commented on _posts/2022-04-10-using-log-collection.markdown
> +right timestamp to the server, due to the buffer knows when the log was
"due to the buffer knowing" or "due to the buffer being aware of"

2022-04-11 15:24 UTC, jakub-dzon commented on _posts/2022-04-10-using-log-collection.markdown
> +In terms of edge device setup, it’s quite easy, for the case of Syslog, the
"It's quite easy to setup an edge device; in case of Syslog, the following config-maps should be in place"

2022-04-12 07:32 UTC, eloycoto commented on _posts/2022-04-10-using-log-collection.markdown
> +the RAM on the device.
not in the current scope, it's something that Roy is also exploring.

2022-04-12 14:57 UTC, jakub-dzon approved these changes

2022-04-12 15:15 UTC, pkliczewski approved these changes

2022-04-12 15:16 UTC, merged