Add documentation
project-flotta/flotta.github.io pull request #3
Opened 2022-03-03 12:04 UTC by machacekondra

Add documentation files to github site.

2022-03-03 14:28 UTC, pkliczewski commented
Do you think it makes sense to keep those files in single place? Maybe we could link it from this repo to `https://github.com/project-flotta/flotta-operator/tree/main/docs`?

2022-03-03 16:02 UTC, machacekondra commented
Right, it's better to keep it in single place let's keep in in flotta operator repo.

2022-03-04 10:25 UTC, pkliczewski approved these changes

2022-03-04 10:32 UTC, jakub-dzon requested changes
Please remove the instructions starting at https://github.com/project-flotta/flotta.github.io/blob/61a1a0892cb6bb5cd8921c39420166d03470bd3b/documentation/index.html#L35.

2022-03-04 15:34 UTC, jakub-dzon approved these changes

2022-03-06 08:43 UTC, masayag approved these changes

2022-03-06 08:43 UTC, merged